### ISSUE TITLE
code running

### ISSUE THREAD

**Issue by CraraW** [JiapengWu/TeMP#5]
Hi ，when I run the code with the command “ python -u main.py -c grid/icews14/config_srgcn.json  --fast-dev-run”，there raise an error  "AttributeError: 'NoneType' object has no attribute 'module'"in trianner.test() .   I found your code has the "test.py".  Does the trianner.test() function need to be called in "main.py"?   Thanks !

- Traceback (most recent call last):
  File "main.py", line 144, in <module>
    trainer.test()
  File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in test
    self.__run_evaluation(test=True)
  File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1479, in __run_evaluation
    can_run_test_step = self.__is_overriden('test_step') and self.__is_overriden('test_end')
  File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 476, in __is_overriden
    model = self.__get_model()
  File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 468, in __get_model
    return self.model.module if self.data_parallel else self.model
AttributeError: 'NoneType' object has no attribute 'module'

**Comment by JiapengWu** [comment]
Hi Crara,

Yes. To run test, please visit readme.md and check the usage. To be honest I never fully run the training until convergence, so I didn’t really use this line ever. I have updated a version that removes this line.

Best,

Paul

On Apr 25, 2021, at 9:42 AM, CraraW ***@***.******@***.***>> wrote:



Hi ，when I run the code with the command “ python -u main.py -c grid/icews14/config_srgcn.json --fast-dev-run”，there raise an error "AttributeError: 'NoneType' object has no attribute 'module'"in trianner.test() . I found your code has the "test.py". Does the trianner.test() function need to be called in "main.py"? Thanks !

  *   Traceback (most recent call last):
File "main.py", line 144, in
trainer.test()
File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in test
self.__run_evaluation(test=True)
File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1479, in __run_evaluation
can_run_test_step = self.__is_overriden('test_step') and self.__is_overriden('test_end')
File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 476, in __is_overriden
model = self.__get_model()
File "/data2/xx/cuda_env/envs/temp/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 468, in __get_model
return self.model.module if self.data_parallel else self.model
AttributeError: 'NoneType' object has no attribute 'module'

**Comment by JiapengWu** [comment]
Hi, I have just uploaded some trained models, please check out the updated readme.

**Comment by CraraW** [comment]
> Hi, I have just uploaded some trained models, please check out the updated readme.

Thank you so much
