### ISSUE TITLE
 trained model  running error

### ISSUE THREAD

**Issue by CraraW** [JiapengWu/TeMP#8]
Hi, thank you for sharing your trained model. But when I use the trained model of BiSARGCN-icews14-complex, there would raise an error.  It seems like  model parameters in the code are not match with the trained model. And there also have the same problem on GRRGCN.
Following are  details about  traceback. Thanks .

command：python  -u test.py  --checkpoint-path ./to_upload/BiSARGCN-icews14-complex-8-0.1-time-embed-only-last-layer-random-dropout/version_202004080949 
./to_upload/BiSARGCN-icews14-complex-8-0.1-time-embed-only-last-layer-random-dropout/version_202004080949/to_upload-BiSARGCN-icews14-complex-8-0.1-time-embed-only-last-layer-random-dropout-version_202004080949-predictions.pk
Traceback (most recent call last):
  File "test.py", line 423, in <module>
    predictions = inference()
  File "test.py", line 406, in inference
    model.load_state_dict(checkpoint['state_dict'])
  File "/data/***/conda-env/.conda/envs/py-lighting/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BiSelfAttentionRGCN:
	Unexpected key(s) in state_dict: "ent_encoder.layer_2.q_linear.bias", "ent_encoder.layer_2.v_linear.bias", "ent_encoder.layer_2.k_linear.bias". 
	
	
command ： python  -u test.py  --checkpoint-path ./to_upload/GRRGCN-icews14-complex-15-0.1-time-embed-only-last-layer-random-dropout/version_202004300606
./to_upload/GRRGCN-icews14-complex-15-0.1-time-embed-only-last-layer-random-dropout/version_202004300606/to_upload-GRRGCN-icews14-complex-15-0.1-time-embed-only-last-layer-random-dropout-version_202004300606-predictions.pk
Traceback (most recent call last):
  File "test.py", line 423, in <module>
    predictions = inference()
  File "test.py", line 406, in inference
    model.load_state_dict(checkpoint['state_dict'])
  File "/data/***/conda-env/.conda/envs/py-lighting/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PostDynamicRGCN:
	Missing key(s) in state_dict: "subject_query_subject_embed_linear.0.weight", "subject_query_subject_embed_linear.0.bias", "subject_query_subject_embed_linear.2.weight", "subject_query_subject_embed_linear.2.bias", "object_query_subject_embed_linear.0.weight", "object_query_subject_embed_linear.0.bias", "object_query_subject_embed_linear.2.weight", "object_query_subject_embed_linear.2.bias", "subject_query_object_embed_linear.0.weight", "subject_query_object_embed_linear.0.bias", "subject_query_object_embed_linear.2.weight", "subject_query_object_embed_linear.2.bias", "object_query_object_embed_linear.0.weight", "object_query_object_embed_linear.0.bias", "object_query_object_embed_linear.2.weight", "object_query_object_embed_linear.2.bias".
	Unexpected key(s) in state_dict: "subject_query_subject_embed_linear.weight", "subject_query_subject_embed_linear.bias", "object_query_subject_embed_linear.weight", "object_query_subject_embed_linear.bias", "subject_query_object_embed_linear.weight", "subject_query_object_embed_linear.bias", "object_query_object_embed_linear.weight", "object_query_object_embed_linear.bias".

**Comment by JiapengWu** [comment]
I will look into the issue in the weekend.

Best.
